### PR TITLE
add support of maven

### PR DESCRIPTION
**Pull request by oldbig**
Add pom.xml, So current project can build with maven.

### CODE REVIEW

**Comment by oldbig** [comment]
Please don't merge, there are dependent problem, please wait for my fix.

**Comment by deanwampler** [comment]
Okay. Will do.

**Comment by deanwampler** [comment]
I'll take a look tomorrow.

**Comment by oldbig** [comment]
Hello @deanwampler 
Ok thank you, that's fine.

I fixed the pom.xml, it can pass test by call:
> mvn test

but I found ComplexSpec2 not executed, when call "sbt test", it executed separate, I do a lot of research, have not found solution. not found other problem. 

sbt test result:
Shuang-screen 2019-06-18 am11 46 16
mvn test result, didn't run ComplexSpec2:
Shuang-screen 2019-06-18 am11 47 00

**Comment by deanwampler** [comment]
Thanks. I couldn't find a resolution either, even when following the Specs2 instructions here, https://etorreborre.github.io/specs2/guide/SPECS2-4.3.4/org.specs2.guide.OtherBuildTools.html. I'll add a note to the README about this.

**Pull request merged**
